-- Migration: Drop orderitems table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

-- Drop trigger
DROP TRIGGER IF EXISTS update_orderitems_updated_at ON orderitems;

-- Drop indexes
DROP INDEX IF EXISTS idx_orderitems_created_at;
DROP INDEX IF EXISTS idx_orderitems_order_id;
DROP INDEX IF EXISTS idx_orderitems_product_id;


-- Drop table
DROP TABLE IF EXISTS orderitems;