-- Migration: Drop orders table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

-- Drop trigger
DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;

-- Drop indexes
DROP INDEX IF EXISTS idx_orders_created_at;
DROP INDEX IF EXISTS idx_orders_customer_id;


-- Drop table
DROP TABLE IF EXISTS orders;