-- Migration: Create orderitems table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.

CREATE TABLE IF NOT EXISTS orderitems (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    product_id UUID NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_orderitems_created_at ON orderitems(created_at);
CREATE INDEX IF NOT EXISTS idx_orderitems_order_id ON orderitems(order_id);
CREATE INDEX IF NOT EXISTS idx_orderitems_product_id ON orderitems(product_id);


-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_orderitems_updated_at
    BEFORE UPDATE ON orderitems
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();