// Package handler provides command handlers for Orderitem entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"github.com/telemetryflow/order-service/internal/application/command"
	"github.com/telemetryflow/order-service/internal/domain/repository"
)

// OrderitemCommandHandler handles commands for Orderitem entity
type OrderitemCommandHandler struct {
	repo repository.OrderitemRepository
}

// NewOrderitemCommandHandler creates a new Orderitem command handler
func NewOrderitemCommandHandler(repo repository.OrderitemRepository) *OrderitemCommandHandler {
	return &OrderitemCommandHandler{
		repo: repo,
	}
}

// HandleOrderitemCreate handles create orderitem command
func (h *OrderitemCommandHandler) HandleOrderitemCreate(ctx context.Context, cmd *command.CreateOrderitemCommand) error {
	entity := cmd.ToEntity()
	return h.repo.Create(ctx, entity)
}

// HandleOrderitemUpdate handles update orderitem command
func (h *OrderitemCommandHandler) HandleOrderitemUpdate(ctx context.Context, cmd *command.UpdateOrderitemCommand) error {
	entity := cmd.ToEntity()
	return h.repo.Update(ctx, entity)
}

// HandleOrderitemDelete handles delete orderitem command
func (h *OrderitemCommandHandler) HandleOrderitemDelete(ctx context.Context, cmd *command.DeleteOrderitemCommand) error {
	return h.repo.Delete(ctx, cmd.ID)
}
