// Package handler provides command handlers for Order entity.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package handler

import (
	"context"

	"github.com/telemetryflow/order-service/internal/application/command"
	"github.com/telemetryflow/order-service/internal/domain/repository"
)

// OrderCommandHandler handles commands for Order entity
type OrderCommandHandler struct {
	repo repository.OrderRepository
}

// NewOrderCommandHandler creates a new Order command handler
func NewOrderCommandHandler(repo repository.OrderRepository) *OrderCommandHandler {
	return &OrderCommandHandler{
		repo: repo,
	}
}

// HandleOrderCreate handles create order command
func (h *OrderCommandHandler) HandleOrderCreate(ctx context.Context, cmd *command.CreateOrderCommand) error {
	entity := cmd.ToEntity()
	return h.repo.Create(ctx, entity)
}

// HandleOrderUpdate handles update order command
func (h *OrderCommandHandler) HandleOrderUpdate(ctx context.Context, cmd *command.UpdateOrderCommand) error {
	entity := cmd.ToEntity()
	return h.repo.Update(ctx, entity)
}

// HandleOrderDelete handles delete order command
func (h *OrderCommandHandler) HandleOrderDelete(ctx context.Context, cmd *command.DeleteOrderCommand) error {
	return h.repo.Delete(ctx, cmd.ID)
}
