// Package fixtures provides test fixtures and utilities for Order-Service.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package fixtures

import (
	"os"

	"github.com/google/uuid"
	"github.com/telemetryflow/order-service/internal/domain"
)

// SetEnvVars sets environment variables for testing and returns a cleanup function
func SetEnvVars(vars map[string]string) func() {
	originalVars := make(map[string]string)

	// Store original values
	for key, value := range vars {
		originalVars[key] = os.Getenv(key)
		_ = os.Setenv(key, value)
	}

	// Return cleanup function
	return func() {
		for key, originalValue := range originalVars {
			if originalValue == "" {
				_ = os.Unsetenv(key)
			} else {
				_ = os.Setenv(key, originalValue)
			}
		}
	}
}

// GetSampleEntity returns a sample entity for testing
func GetSampleEntity() *domain.Entity {
	return domain.NewEntity(uuid.New(), "Test Entity")
}

// GetSampleEntities returns a slice of sample entities for testing
func GetSampleEntities(count int) []interface{} {
	entities := make([]interface{}, count)
	for i := 0; i < count; i++ {
		entities[i] = domain.NewEntity(uuid.New(), "Test Entity")
	}
	return entities
}

// GetSampleEntityData returns sample entity data for HTTP request body
func GetSampleEntityData() map[string]interface{} {
	return map[string]interface{}{
		"name": "Test Entity",
	}
}
