// Package domain provides domain types and utilities.
//
// Generated by TelemetryFlow RESTful API Generator
// Copyright (c) 2024-2026 DevOpsCorner Indonesia. All rights reserved.
package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
)

// Common domain errors
var (
	ErrEntityNotFound = errors.New("entity not found")
	ErrInvalidEntity  = errors.New("invalid entity")
)

// Entity represents a generic domain entity for testing purposes
type Entity struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewEntity creates a new Entity with the given ID and name
func NewEntity(id uuid.UUID, name string) *Entity {
	now := time.Now()
	return &Entity{
		ID:        id,
		Name:      name,
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// NewEntityWithValidation creates a new Entity with validation
func NewEntityWithValidation(id uuid.UUID, name string) (*Entity, error) {
	if err := ValidateEntityName(name); err != nil {
		return nil, err
	}
	return NewEntity(id, name), nil
}

// ValidateEntityName validates an entity name
func ValidateEntityName(name string) error {
	if name == "" {
		return errors.New("name cannot be empty")
	}
	if len(name) > 255 {
		return errors.New("name exceeds maximum length")
	}
	return nil
}
